# for pre-ari.lt see netlify.toml.old

[[redirects]]
    from = "/*"
    to = "https://legacy.blog.ari.lt/:splat"
    status = 301
    force = true

# Processing
[build.processing]
    skip_processing = false

[build.processing.html]
    pretty_urls = false

[build.processing.css]
    bundle = true
    minify = true

[build.processing.js]
    bundle = true
    minify = true

[build.processing.images]
    compress = true
# --------------

[[headers]]
    for = "/*"

    [headers.values]
        Strict-Transport-Security = "max-age=0"
        X-Frame-Options = "deny"
        X-Content-Type-Options = "nosniff"
        Content-Security-Policy = "upgrade-insecure-requests"
        X-Permitted-Cross-Domain-Policies = "none"
        Referrer-Policy = "no-referrer"

